export const FETCH_MOVIES = 'FETCH_MOVIES';
export const FETCH_MOVIES_FAILURE = 'FETCH_MOVIES_FAILURE';
export const SET_MOVIES = 'SET_MOVIES';
export const TOGGLE_FAVORITE = 'TOGGLE_FAVORITE';
export const SET_FAVORITE_MOVIES = 'SET_FAVORITE_MOVIES';
export const CLEAR_MOVIES_FROM_LS = 'CLEAR_MOVIES_FROM_LS';
